/*  OrderControl.xaml.cs
*   Author: Nick Monaco
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DinoDiner.Menu;

namespace PointOfSale {
    /// <summary>
    /// Interaction logic for OrderControl.xaml
    /// </summary>
    public partial class OrderControl : UserControl {

        /// <summary>
        /// The constructor for OrderControl.
        /// Automatically generated by Visual Studio.
        /// </summary>
        public OrderControl() {
            InitializeComponent();
        }

        /// <summary>
        /// Handles what happens when an 'X' button is clicked on an item in the order.
        /// </summary>
        /// <param name="sender">The 'X' button being clicked.</param>
        /// <param name="args">The RoutedEventArgs tied to this event.</param>
        public void OnDeleteClick(object sender, RoutedEventArgs args) {
            Button b = sender as Button;
            IOrderItem item = b.Tag as IOrderItem;

            if (DataContext is Order order && item != null) {
                order.Items.Remove(item);
            }
        }

        /// <summary>
        /// Handles what happens when the "Cancel" button is clicked, which clears all items from the order.
        /// </summary>
        /// <param name="sender">The "Cancel" button being clicked.</param>
        /// <param name="args">The RoutedEventArgs tied to this event.</param>
        public void ClearClick(object sender, RoutedEventArgs args) {
            if (DataContext is Order order) {
                order.Items.Clear();
            }
        }
    }
}
