/*  Index.cshtml.cs
*   Author: Nick Monaco
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Website.Pages
{
    public class IndexModel : PageModel
    {
        /// <summary>
        /// The OnGet function, generated by Visual Studio.
        /// </summary>
        public void OnGet()
        {

        }
    }
}
